{}

[21:54:09] [L] My Cmd  : Welcome to My CMD
[21:54:11] [R] My Cmd  : userlist
[21:54:11] [E] My Cmd  : 
-------------- Error                --------------------
Type: TypeError

More information:
	__init__() takes 1 positional argument but 2 were given	

Traceback (most recent call last):
  File "D:\Documents\GitHub\NewLifeUtils\NewLifeUtils\CustomShellModule.py", line 346, in main
    registered["run"](self)
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 40, in userlist
    User('Kotaz')
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 31, in __init__
    super(User, self).__init__()
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 20, in __init__
    self.uuid = DataSector(uuid.uuid4())
TypeError: __init__() takes 1 positional argument but 2 were given

-------------- Error                --------------------

[21:54:44] [R] My Cmd  : exit
[21:54:44] [L] My Cmd  : Exit with code: quit, from: None
[21:54:45] [L] My Cmd  : Welcome to My CMD
[21:54:47] [R] My Cmd  : userlist
[21:54:47] [E] My Cmd  : 
-------------- Error                --------------------
Type: RecursionError

More information:
	maximum recursion depth exceeded while calling a Python object	

Traceback (most recent call last):
  File "D:\Documents\GitHub\NewLifeUtils\NewLifeUtils\CustomShellModule.py", line 346, in main
    registered["run"](self)
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 40, in userlist
    User('Kotaz')
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 31, in __init__
    super(User, self).__init__()
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 20, in __init__
    self.uuid = DataSector(uuid.uuid4())
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 20, in __init__
    self.uuid = DataSector(uuid.uuid4())
  File "D:\Documents\GitHub\NewLifeUtils\test.py", line 20, in __init__
    self.uuid = DataSector(uuid.uuid4())
  [Previous line repeated 492 more times]
  File "c:\python39\lib\uuid.py", line 715, in uuid4
    return UUID(bytes=os.urandom(16), version=4)
  File "c:\python39\lib\uuid.py", line 170, in __init__
    if [hex, bytes, bytes_le, fields, int].count(None) != 4:
RecursionError: maximum recursion depth exceeded while calling a Python object

-------------- Error                --------------------

[21:55:24] [R] My Cmd  : exot
[21:55:24] [W] My Cmd  : Unknown Command, type "help"
[21:55:25] [R] My Cmd  : exit
[21:55:25] [L] My Cmd  : Exit with code: quit, from: None
